#!/usr/bin/env bash
#
# This script installs moonshell to $PATH
#

set -eu
# To set debug mode for this script `export DEBUG=true` prior to running
# Use `unset DEBUG` to return to normal usage.
[[ ${DEBUG-} ]] && set -x

REPO="$(basename $0)"
REPO_DIR="${PWD}/$(dirname $0)"
BIN_DIR="${REPO_DIR}/bin"
MOON_HOME="${HOME}/.moonshell"

echoerr() {
    echo "${@-}" >&2
}

not_installed() {
    # a `grep -c` of zero == not present, so return true
    local retr=$(grep -v '^#' ${HOME}/${BASH_FILE} | grep -c "${MOON_HOME}/moon.sh" 2>/dev/null)
    return ${retr}
}

gem_not_installed() {
    local gem=$1
    [[ ! -f ${MOON_HOME}/Gemfile.lock ]] && return 0
    local retr=$(grep -c ${gem} ${MOON_HOME}/Gemfile.lock)
    return ${retr}
}

case $(uname) in
    Linux) BASH_FILE=".bashrc";;
    Darwin) BASH_FILE=".bash_profile";;
    *)
        echoerr "ERROR: Somehow \`uname\` returned something other than 'Linux' or 'Darwin'"
        echoerr ""
        echoerr "   o_0"
        echoerr " ~\_|_/~"
        echoerr "    |"
        echoerr "  _/ \_"
        exit 1
    ;;
esac

#
# Standard Symlink
#
[[ ! -L ${HOME}/.moonshell ]] && ln -s ${REPO_DIR} ${MOON_HOME}


#
# Bash Sourcing
#
if not_installed; then
    echoerr "To install moonshell in to your \$PATH, press enter; else CTRL-C"
    read
    echo >> ${HOME}/${BASH_FILE}
    echo "# Moonshell: because setting up Bash for managing space travel shouldn't be a moonshot" >> ${HOME}/${BASH_FILE}
    echo "#export DEBUG=true" >> ${HOME}/${BASH_FILE}
    echo "source ${MOON_HOME}/moon.sh" >> ${HOME}/${BASH_FILE}
    echoerr "Installation complete.."
    echoerr "To use the \$PATH ammendment, respawn your shell."
else
    echoerr "Installation not required"
fi


#
# Private Dirs
#
[[ ! -d ${MOON_HOME}/lib/private ]] && mkdir ${MOON_HOME}/lib/private
[[ ! -d ${MOON_HOME}/profile.d/private ]] && mkdir ${MOON_HOME}/profile.d/private


#
# Ruby Gems
#
GEMS=($(grep ^gem "${MOON_HOME}/Gemfile" | tr -d "'" | awk '{print $2}'))
for gem in ${GEMS[@]}; do
    if gem_not_installed ${gem}; then
        echoerr "Installing ruby gems"
        pushd ${MOON_HOME} >/dev/null
            bundle install
        popd >/dev/null
    fi
done
